# Site
name: "Rodrigo Farinha"
title: "Rodrigo Farinha"
description: "Rodrigo Farinha"
logo: 'assets/images/rodrigo_farinha.jpg' # Update with actual path later
favicon: 'assets/images/favicon.ico' # Update with actual path later
baseurl: "" # Set for root deployment
google_analytics: '' # Add Rodrigo's GA ID if provided
disqus: '' # Add Rodrigo's Disqus shortname if provided
mailchimp-list: '' # Add Rodrigo's Mailchimp list if provided
include: ["_pages"]
permalink: /:title/
email: '' # Add Rodrigo's email if provided

# Authors
authors:
  rodrigo:
    name: Rodrigo Farinha
    display_name: Rodrigo L. Farinha
    avatar: 'assets/images/rodrigo_farinha.jpg' # Update with actual path later
    email: '' # Add Rodrigo's email if provided
    web: '' # Add personal website URL once deployed
    twitter: '' # Add Twitter URL if provided
    linkedin: 'https://www.linkedin.com/in/rodrigolourencofarinha?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app'
    description: "PhD in Marketing. Consultant & Scholar focused on go-to-market strategy, digital transformation, and innovation, particularly in agribusiness and B2B sectors."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge # Changed from none to enable syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, docker-compose.yml, site]
