title: "Rodrigo Farinha"
description: "PhD Candidate at Fundação Getulio Vargas"
url: "https://rodrigolourencofarinha.github.io"
baseurl: ""
author:
  name: "Rodrigo Farinha"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"