# Site
name: "Rodrigo Farinha"
title: "Rodrigo Farinha"
description: "Rodrigo Farinha"
logo: 'assets/images/rodrigo_farinha.jpg' # Update with actual path later
favicon: 'assets/images/favicon.ico' # Update with actual path later
baseurl: "" # Set for root deployment
google_analytics: 'G-GETFNJX2YC' # Add Rodrigo's GA ID if provided
# Disqus deprecated in favor of Giscus
disqus: ''
# Giscus configuration (GitHub Discussions-based comments)
giscus:
  repo: 'rodrigolourencofarinha/rodrigolourencofarinha.github.io'            # e.g., owner/repo
  repo_id: 'R_kgDOM-fc0g'         # optional, from Giscus setup
  category: 'General'        # e.g., Announcements (name)
  category_id: 'DIC_kwDOM-fc0s4Cutth'     # optional, from Giscus setup
  mapping: 'pathname' # pathname | url | title | og:title | specific
  strict: 0           # 0 | 1
  reactions_enabled: 1# 0 | 1
  emit_metadata: 0    # 0 | 1
  input_position: 'bottom' # top | bottom
  theme: 'preferred_color_scheme'      # light | dark | preferred_color_scheme | etc.
  lang: 'en'          # interface language
mailchimp-list: '' # Add Rodrigo's Mailchimp list if provided
include: ["_pages"]
permalink: /:title/
email: '' # Add Rodrigo's email if provided

# Authors
authors:
  rodrigo:
    name: Rodrigo Farinha
    display_name: Rodrigo Farinha
    avatar: 'assets/images/rodrigo_farinha.jpg' 
    email: 'rodrigo.farinha@tuta.io' 
    web: 'https://rodrigofarinha.com' 
    twitter: 'https://x.com/RodrigoLFarinha' 
    linkedin: 'https://www.linkedin.com/in/rodrigolourencofarinha'
    description: "PhD in Marketing. Consultant & Scholar focused on go-to-market strategy, digital transformation, and innovation, particularly in agribusiness and B2B sectors."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge # Changed from none to enable syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Home layout options
home_hero: false

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, docker-compose.yml, site]
